### ISSUE TITLE
Revisit default date formats

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/repeating_dates#12]
The module uses some different date formats. Here's an example of four to five different formats on node display:

- `Wed, 11/10/2021 - 4:57pm` (node info, so *not* from the module, but may add to the confusion of different formats)
- `11/17/21` (from the summary text)
- `2021-12-01` (exception date)
- `11/17/2021 - 12:00pm – 15:00:00` (an actual date, note the different time formats as well)

Can the formats be harmonized? And/or is there a way to tweak them?

**Comment by olafgrabienski** [comment]
> And/or is there a way to tweak them?

Now I see, the formats *can* be configured in the field's display settings. The defaults on my test site were:

- Full datetime format is Short Date
- Date only format is HTML Date
- Time only format is HTML Time

I've changed the Full datetime format to HTML Datetime, so that the configuration looks pretty consistent:

- Full datetime format is HTML Datetime
- Date only format is HTML Date
- Time only format is HTML Time

The result (without the node info) looks also better than before, but it's still a format mix:

- `11/17/21` (in the summary text, not configurable?)
- `2021-12-01` (exception date, ok)
- `2021-11-17T12:00:00+0100 – 15:00:00` (still different time formats, and HTML Datetime is quite verbose)

Given a HTML like format, I'd expect rather something like the following:

- `2021-11-17` (in the summary text)
- `2021-12-01` (exception date)
- `2021-11-17, 12:00 to 15:00` (an actual date)

I'm not sure if there's a reasonable approach to achieve a comparable consistency, and it may be even more difficult for different format 'types' (e.g. HTML and Short/Medium/Long). But to make a start, a configurable date for the summary text would be helpful.

**Comment by indigoxela** [comment]
> I'm not sure if there's a reasonable approach to achieve a comparable consistency,

Totally easy, go to /admin/config/regional/date-time and add your desired formats. Then they'll appear in the format select list.
This might need better documentation.

**Comment by olafgrabienski** [comment]
> Totally easy, go to /admin/config/regional/date-time and add your desired formats.

Sure, for individual sites, and that's a great option! Only, the date in the summary text isn't configurable. And it makes also sense to improve the defaults, in my opinion.

**Comment by indigoxela** [comment]
> Only, the date in the summary text isn't configurable.

That's currently "outside" the module, see also https://github.com/backdrop-contrib/repeating_dates/issues/4

**Comment by indigoxela** [comment]
> And it makes also sense to improve the defaults, in my opinion.

The problem is: which format?

No format exists, that fits all languages/countries (12-hour vs. 24 hour format, date and month order...), so it seems futile to even try, when we already know, people have to and will (and can) adapt it anyway.
