### ISSUE TITLE
Improve order and appearance of form elements

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/repeating_dates#13]
First: I'm aware that to build a repeating date form with good usabiliy is a big challenge. In my opinion, the existing form works already good, if you know how it works. But when I tested the module for the first time, primarily with weekly repeats, I made a couple of mistakes:

- I didn't choose a weekday for different reasons. First I assumed the weekday would be chosen automatically based on the Start date. Later on, sometimes I just forgot to choose the weekday.
- In other cases I chose a 'wrong' weekday, i.e. which didn't correspond to the Start date. When I chose the intended weekday after saving the node, in some cases (if I recall correctly) the originally intended Start date was changed, but I didn't notice that immediately, and so on.
- At the beginning, It was not clear to me that I can choose multiple weekdays.

One reason for my mistakes is that the Start date doesn't show the weekday when it's selected. Not sure if this can be fixed in a reasonable way, and there are probably more reasons, but I haven't identified all of them.

However, for me the form would be much easier to understand and to manage, if it would start with the "Repeats Every" section. See the screenshots in the following comment for comparison. What do others think?

**Comment by olafgrabienski** [comment]
## Current form

![backdrop-repeating-dates-widget-order-1](https://user-images.githubusercontent.com/14188307/141165745-50893044-7775-402f-a85d-98350e4bca96.png)

## Proposal / mockup

![backdrop-repeating-dates-widget-order-2](https://user-images.githubusercontent.com/14188307/141165752-37c5053b-3537-4d11-8e60-cfed441f418d.png)

(paddings to be adjusted)

**Comment by olafgrabienski** [comment]
> At the beginning, It was not clear to me that I can choose multiple weekdays.

Plain checkboxes without extra styles are better to understand, in my opinion. Comparison:

## Current checkboxes

![backdrop-repeating-dates-checkboxes-1](https://user-images.githubusercontent.com/14188307/141169721-ffd09505-9e0b-46eb-9128-0262facc62fc.png)

## Plain checkboxes

![backdrop-repeating-dates-checkboxes-2](https://user-images.githubusercontent.com/14188307/141169727-659f5886-2add-4c72-9f59-92386b478233.png)

**Comment by indigoxela** [comment]
Many thanks for your mockups.

To be honest, I don't think that moving the start below the repeat select is an improvement.

Same for the checkboxes, which have been styled like that intentionally. I find them a lot better as they currently are (button-style).

**Comment by indigoxela** [comment]
> One reason for my mistakes is that the Start date doesn't show the weekday when it's selected.

You might also have missed, that the start's weekday doesn't actually matter. The start gets handled like "start with or after that date".

**Comment by olafgrabienski** [comment]
> The start gets handled like "start with or after that date".

Yes, it took a while to get it, and it added to my confusion.

**Comment by olafgrabienski** [comment]
> I don't think that moving the start below the repeat select is an improvement.

Fair enough! I'm also curious what others think. @laryn and @yorkshire-pudding what do you think about the ideas re element order and checkbox styling?

**Comment by olafgrabienski** [comment]
Btw, on Drupal's [Recurring Date Field Modular Widgets](https://www.drupal.org/project/date_recur_modular) project page I see two of three forms which start with the the repeat mode. Doesn't seem to be so uncommon then ... and probably also a question of personal preference. So maybe another option for the [settings](https://github.com/backdrop-contrib/repeating_dates/issues/5)?

**Comment by yorkshire-pudding** [comment]
@olafgrabienski @indigoxela - I don't have a preference on whether the start date is before or after the repeat.  I can see the logic in both approaches.  In google calendar, start is before repeat.

I like the bigger target of the buttons for weekdays, though one thing I notice with Olaf's idea is the contrast is greater.  Strike-through is clear and unambiguous but would an inverted colour in addition so the difference is more striking help?
![image](https://user-images.githubusercontent.com/20357797/141279403-c181c791-2943-4a8f-b317-a1bd2be468ff.png)

**Comment by indigoxela** [comment]
I just played a bit with the form item order.

Start input right before stop input is OK with "Daily" and "Weekly", seems a bit confusing with "Monthly" and "Yearly" and is totally odd with "Do no repeat". IMO, as it only works well with two out of five options, I'd rather not switch the order.

**Comment by indigoxela** [comment]
@yorkshire-pudding yes, the contrast might need a little tweak (it's AA, though).
I'm not sure, if the very dark (black) background really communicates "this is selected". To me this combination rather feels like disabled, broken, unavailable... At least with lighter themes like Seven. (And IMO the style shouldn't be too specific to one theme.)

**Comment by yorkshire-pudding** [comment]
@indigoxela You're right, that was one possible example but as people can have their regular theme for editing and adding content it needs to be compatible - not sure how to do with different themes - perhaps font weight or border thickness.  Just needs to be a bit more difference so it's obvious which is selected and which isn't from a glance.  I'm probably just nitpicking though as the UI looks good as is an improvement on any repeat dates functions I've seen before

**Comment by olafgrabienski** [comment]
> I just played a bit with the form item order.

Thanks for having another look! I don't exactly share your impression regarding "Do not repeat", but I understand perfectly if you don't want to change the order.

**Comment by indigoxela** [comment]
Regarding better highlighting of selected weekdays: how about an underline (sort of)?

![highlight-day](https://user-images.githubusercontent.com/842066/141443761-0677d3d1-9202-4890-88d9-ad3821ebddf0.png)

**Comment by yorkshire-pudding** [comment]
Yes - looks good

**Comment by yorkshire-pudding** [comment]
@indigoxela - I think this can be closed as its in the current Alpha release
