### ISSUE TITLE
"to" time format.

### ISSUE THREAD

**Issue by echozone** [backdrop-contrib/repeating_dates#14]
I've read through closed issue #12. How can we adjust this "to" part of the format?

4/12/2022 - 1:00pm – 15:00:00

Why is it just the "to"? I've tried on the clean demo, I can't effect the "to" part of the time, am I missing something?

**Comment by indigoxela** [comment]
Hi @echozone,

I belief, what you're searching for is the "Time only format" setting:

![field-display](https://user-images.githubusercontent.com/842066/163110434-2011122b-a8dc-4524-b5a8-e49258436539.png)

The format doesn't exist on a fresh install, so you probably also have to create that yourself.

1. Go to /admin/config/regional/date-time and create it
2. Adapt the field display, for instance on /admin/structure/types/manage/YOURTYPE/display/default

Does that help?

**Comment by echozone** [comment]
Yes perfect, thank you for that! I had already made those custom formats :-)

I'm having more serious issues with how this field seems different in views than other date fields. If I try to add a filter for Date (node), this date field is not listed among the (required) Date fields to select a checkbox for.

I'm doing a D7 migration where I used repeating date fields significantly, and I'm swapping this one in for most of the D7 date + repeating date. I could use help on that. 

It has some nice features, thanks for your work on this. I can help with testing.

**Comment by indigoxela** [comment]
> I'm doing a D7 migration where I used repeating date fields significantly

I'm not sure if that would work. Date Repeat (D7) and Repeating Dates (B) are *very different* field types.

I don't understand your views problem yet (struggling to follow your description), mind to open a new issue for that, so we can figure out?

I'll close this one - you question regarding formatting seems answered, right?

**Comment by echozone** [comment]
Yes, formatting addressed, thx. Yes obviously different, I'll write something up in a new issue tomorrow... sleep now. thank you so much for helping :-)
