### ISSUE TITLE
view not working

### ISSUE THREAD

**Issue by echozone** [backdrop-contrib/repeating_dates#15]
@indigoxela here's a summary of the issue with this repeating_dates field + views.

2 content types using this date field.

3 views, 1 for each content type, a third is an upcoming block including both content types.

2 views are working, including the block.

The broken view is not showing anything (but it's content is showing up in the upcoming block).

The broken view has an error right above the preview:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_data_field_date.field_date_value' in 'order clause'

===========
All are set up with this, relevant to the date field (named "Date Time"):

SORT: Content: Date Time:dtstart (asc)

FILTER: 
working block:
  Content: Date Time:dtend (>= now)
working view:
  Content: Date Time:dtstart (<= now)
broken view:
  tried both

FIELDS: date field, multiple: 
working block: unchecked
working view: checked
broken view: tried both

**Comment by indigoxela** [comment]
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_data_field_date.field_date_value' in 'order clause'

Yes, the column "value" only exists on core date fields. To sort Repeating Dates fields, you have to use `Content: Dates (repeating):dtstart (asc)`.

Although you posted that as your sorting criteria, there must be something wrong with your sorting setup. as the database query still shows the core date field column to be in use for "order by".

Can you post the json export of that view?

**Comment by echozone** [comment]
I should have recognized the core date field name in that error! config file attached as requested. Deleted obsolete attached.

Deleted obsolete attached.

The view's config file doesn't seem to contain any reference to the core date field (also couldn't find anything to suspect in the db).

The content type called in the view has it's date field updated to repeating_dates, but certainly there's past content using core date, which I'll need to delete. Maybe this is where the error is pulling from?

The other view (listing different repeating date content) has a flaw, but content shows up, + there's no error. The block has been deleted.

Question... can repeating_dates be used on some content types, while on the same site, different content types use only core date?

**Comment by indigoxela** [comment]
> The content type called in the view has it's date field updated to repeating_dates,

So if I get it right, you have mixed content. In other words, you have both, the core date and the repeating date field attached to that content type? And you try to order the view by the repeating date start? But older nodes don't have content in that. Phew... not sure if that will work.

> can repeating_dates be used on some content types, while on the same site, different content types use only core date?

Sure, without any problem.

It's also possible to use both fields on the same content type, but creating a view that combines both results seems a bit tricky. I know that it works with Fullcalendar Views NG and additional source as json feed, but your setup seems a bit tricky, so I doubt I can help you with that. Probably you'll have to figure out yourself.

BTW. the Repeating Dates fields can also have only one value ("Do not repeat").

**Comment by echozone** [comment]
To follow up,
As long as I keep the 2 core fields (date + repeat) as Sort criteria along with the repeating_dates field, the error is not there + there are results from the view. Removing either results in the error + no results. The sort is a bit screwed up, likely from having those other 2 fields needing to be there.

There is none of either core date field (date + repeat) in the content type. I eventually removed ALL the nodes of that type from the site. The error remained in the same way. There is none of either core date field (date + repeat) in the content type or in the new sample nodes (yes, they use either multiple + single value).

What would still be looking for this column to generate this error? It's a mystery I might take to the forum.

A second content type with it's own view + a block displaying from both content types work, + never had this issue.

**Comment by indigoxela** [comment]
> What would still be looking for this column to generate this error?

Hard to tell when knowing so little about your site and setup.

> It's a mystery I might take to the forum.

That sounds like a plan.
