### ISSUE TITLE
Display one of multi repeating_dates field in view, while it disappears after it's date has passed

### ISSUE THREAD

**Issue by echozone** [backdrop-contrib/repeating_dates#16]
I have a view listing a content type using one repeating_dates field (thx @indigoxela). The content type has some nodes choosing repeating, and some nodes choosing "Do not repeat". It is the same field.

What I can't get to work is a node disappears from the view after it's date has passed.

This is because the the only way I have found to get a multiple field node to display only one instance, is to filter thedatefield:delta (= 0).

But that includes all the single dated nodes, past + future, as all are delta = 0.

What works for the single dated node, is using the filter of either thedatefield start or end >= now.

But that keeps multiples with delta = 0 showing up, since their delta = 0 is in the past.

I've tested many filter group options, grouping variations of these filters with -And Or- Operators.

Enabling Distinct or aggregation is no help.

In D7, it worked by filtering Date (node). This only includes core date fields to check, the repeating_dates field doesn't show up.

What are other ways to get a multi repeating_dates field to show only one?

Over at the [forum](https://forum.backdropcms.org/forum/display-one-multi-repeatingdates-field-view-while-it-disappears-after-its-date-has-passed), @argiepiano suggested an enhancement to the date handler. I'm available for testing of course.

**Comment by indigoxela** [comment]
> What I can't get to work is a node disappears from the view after it's date has passed.

Seems like another time I'm having trouble to understand the problem. :wink: 

It works for me. A FC view with repeating dates, additional filter on `Content: Dates (repeating):dtstart (>= today)` and the passed dates are gone. No fiddling with delta, no other adaptions.

**Comment by indigoxela** [comment]
Some screenshots how to only display the first date of repeating ones filtered for dates in the future:

![view-setting](https://user-images.githubusercontent.com/842066/165703891-1d73a672-9592-4743-80ae-484b9bd92e5a.png)
![views-multi-setting](https://user-images.githubusercontent.com/842066/165703916-7c187df2-c485-48fb-9767-7efdde5b7a34.png)
![view-cal-result](https://user-images.githubusercontent.com/842066/165703944-56d71a9c-f76d-4882-8f99-4e48a113ae51.png)

As you can see, the "bi-weekly" (which repeats) only shows up once.

**Comment by echozone** [comment]
See the view NOT using Fullcalendar NG.

**Comment by argiepiano** [comment]
@indigoxela , @echozone wants to hide dates that are in the past for a repeating date field in a non-calendar display

**Comment by indigoxela** [comment]
> wants to hide dates that are in the past for a repeating date field in a non-calendar display

Ah, now I get it. The approach is the same, though. I switched the same view to "unformatted list" and only the first date shows up.

**Comment by indigoxela** [comment]
Here's a screenshot:

![unformatted-list](https://user-images.githubusercontent.com/842066/165779663-f8059283-602d-49b6-80b4-c94d39887805.png)

**Comment by echozone** [comment]
Odd, when I use both Filters: delta (= 0) and dtstart (>= now) only the not repeating future date shows. Can you test just adjusting your repeating date node spanning from the past into the future?

From my original description,
"What works for the single dated node, is using the filter of either thedatefield start or end >= now.

But that keeps multiples with delta = 0 showing up, since their delta = 0 is in the past."

**Comment by indigoxela** [comment]
> Can you test just adjusting your repeating date node spanning from the past into the future?

Sure, that also works as expected - the (now in past) date isn't displayed anymore in that view.

**Comment by echozone** [comment]
Your screenshot shows using both filters:
:dtstart (>=now)
:delta (=0)
How are you getting the multi repeating_dates field to show only one?

"
the only way I have found to get a multiple field node to display only one instance, is to filter thedatefield:delta (= 0).

But that includes all the single dated nodes, past + future, as all are delta = 0.

What works for the single dated node, is using the filter of either thedatefield start or end >= now.

But that keeps multiples with delta = 0 showing up, since their delta = 0 is in the past.
"

**Comment by indigoxela** [comment]
> How are you getting the multi repeating_dates field to show only one?

That's exactly the same view as in the screenshots above, I just switched the display.

Here's a screenshot of the views field setting (dialog):
![views-field-setting](https://user-images.githubusercontent.com/842066/165973721-d19466ff-4ca5-4e1a-aee0-929213e82284.png)

**Comment by indigoxela** [comment]
As you seem to have trouble with the filter settings - here's a screenshot that clarifies how my view filter is set up:

![views-filters](https://user-images.githubusercontent.com/842066/165975127-b17692ce-9b52-4a18-bccb-daed31f1be0c.png)

**Comment by echozone** [comment]
Same here, but the filters are the issue.
delta 0 is the first instance in a multiple, and the only instance in a single. 

My issue makes sense. delta (=0) shows the first only of the multiple. When the first becomes in the past, all instances of the multiple disappear. We need to show other instances of the multiple. Actually, if we could get delta "last" it would work, but I believe delta is numeric.

What logic has one instance of your multiple still showing, if you are filtering for delta = 0 after the first has moved to the past?

**Comment by echozone** [comment]
Simplified new TestView view of TestCT with field DateR.
4 test nodes. CT1 + CT2 are single, CT3 + CT4 are repeating.

Only CT2, the future single, shows up.
CT3 + CT4 are still current, but are filtered out since delta 0 has past.

=====
![view](https://user-images.githubusercontent.com/2477719/166035191-9c434e72-5e19-4fa7-bf32-8da149abe4ad.png)

=====
![field](https://user-images.githubusercontent.com/2477719/166037774-d67b469b-4ce7-4a32-986b-b6e9183480dd.png)

=====
![filter](https://user-images.githubusercontent.com/2477719/166039125-691e5ef4-2b56-4aa0-bdf1-8b81752478eb.png)

=====
![result](https://user-images.githubusercontent.com/2477719/166039866-247386a6-8c4c-47a9-8271-93c71a1fbd1c.png)

=====
[views.view.testview.json.zip](https://github.com/backdrop-contrib/repeating_dates/files/8593208/views.view.testview.json.zip)

=====
@indigoxela I really do appreciate your patience!

**Comment by indigoxela** [comment]
> We need to show other instances of the multiple.

That sound a little different. You want ... let me guess ... the first of multiple, still in the future, but not necessarily the first by delta? Then you can not use the filter "delta = 0" at all, because then it's really only the first value in that field.

Sounds tricky - and it's not related to the field type at all, because that problem's the same with *every* multi-value field type. Note that "delta" is the value from the database, not "the first after applying another filter".

I don't think I can help you with that generic views (database query) logic problem. You'll have to figure out yourself.

**Comment by indigoxela** [comment]
Spoken too soon... it IS possible with aggregation, but a bit complicated.

1. Remove the delta filter
2. Turn on aggregation (Views admin table, right column)
3. Set up as in following screenshots

![views-settings](https://user-images.githubusercontent.com/842066/166101637-3f68d348-596d-404e-b69d-0a360f0adcdd.png)

![aggregate-setting](https://user-images.githubusercontent.com/842066/166101644-d4f44e6e-a103-4c0d-85f9-446f6b711b49.png)

**Comment by echozone** [comment]
That hid the dates in the past, but showed all multiple ones in the future. Thanks for the effort.

I'm going to settle with hiding all once the first moves to the past, since a training can't be joined once it begins, and there's an separate upcoming block that shows all (that works because it's limited to 5).

Recall I mentioned In D7, it worked by filtering Date (node), if there's an enhancement that can be done on the date handler, which I don't understand. Thank you for this module!

**Comment by indigoxela** [comment]
> That hid the dates in the past, but showed all multiple ones in the future

Doesn't in my test view, though. In my view multiples get filtered correctly. I suspect, you do additional sorting, which brings back the multiple ones.

> Recall I mentioned In D7, it worked by filtering Date (node)

This module does not exist for D7, it's been written for B specifically, so you compare apples and oranges.

> if there's an enhancement that can be done on the date handler

There isn't. Technically this all works as expected. (And again, it works for me.)

**Comment by echozone** [comment]
You're right, I removed my sort (start asc) then put it back, and it filters to one of each multiple, and all works!  Thanks again!
