### ISSUE TITLE
"Add Exception" only allows one entry

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/repeating_dates#2]
Clicking the "Add Exception" button more than once seems to give the ajax spinner but do nothing.

**Comment by indigoxela** [comment]
> Clicking the "Add Exception" button more than once seems to give the ajax spinner but do nothing.

That's a UX problem - I know. As long as you didn't set a value in the exdate field, no additional field gets added. Actually it does reload, but only one empty field is available, so it appears to not have done anything. For sure not easy to discover.

**Comment by indigoxela** [comment]
I [now removed the filtering](https://github.com/backdrop-contrib/repeating_dates/commit/b56842d4bf2dcda70b9de262163e6ec3e26e2882) of empty values when adding exdates - @laryn does this seem more comprehensive for you?

**Comment by olafgrabienski** [comment]
Just tested the changed behavior, looks good to me! I'm able to add more then one exception date without any problem, even if I don't set any value before adding new instances of the exception dates.

**Comment by indigoxela** [comment]
@olafgrabienski many thanks for testing. Closing this as fixed now.
