### ISSUE TITLE
Settings for default Weekdays and Stop based on method

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/repeating_dates#23]
As a site builder
I want to set the default 'Weekdays' and 'Stop based on' method (i.e. Count/Date) for a content type
So that it is as easy as possible for editors to add repeating patterns where I know that this will always be the setting for that content type

I had a quick look at the code, but couldn't workout exactly how I needed to add it.  If you can point me to which files (and ideally functions) I need to look at, I don't mind having a go.

**Comment by indigoxela** [comment]
> set the default 'Weekdays' and 'Stop based on' method (i.e. Count/Date) for a content type

I see... the "Weekdays" setting might be tricky, as it's only there with weekly repeats.

You can have full control with hook_form_alter, BTW.

Here's an example:
```
/**
 * Implements hook_form_FORM_ID_alter().
 */
function YOURTHING_form_node_form_alter(&$form, &$form_state, $form_id) {
  // Nothing to do if not our type.
  if ($form['#node']->type != 'YOUR_NODE_TYPE') {
    return;
  }

  // This is a new node.
  if (empty($form['#node']->nid)) {
    // "freq" is also available via UI, but for completeness...
    $form['field_dates_repeat'][LANGUAGE_NONE]['rrule']['freq']['#default_value'] = 'weekly';
    $form['field_dates_repeat'][LANGUAGE_NONE]['rrule']['byday_week']['#default_value'] = array('SU');
    $form['field_dates_repeat'][LANGUAGE_NONE]['rrule']['stopby']['#default_value'] = 'date';
    // Dynamic end date.
    $until = new DateTime('+5 months', date_default_timezone_object());
    $form['field_dates_repeat'][LANGUAGE_NONE]['rrule']['until']['#default_value'] = $until->format('Y-m-d');
  }
}
```
Just replace YOURTHING with your module or theme name and YOUR_NODE_TYPE with the node type the repeat field is attached to.

Oh, and replace "field_dates_repeat" with your field name. :wink:

**Comment by yorkshire-pudding** [comment]
Wow - thanks @indigoxela - that works a treat.  I may well build this module up with some other functions around this use case.  The more I learn about Backdrop and what is possible, the more I love it.  Happy to close if you don't think that it's feasible to do.

**Comment by indigoxela** [comment]
> Happy to close if you don't think that it's feasible to do.

It's probably feasible, but my concern is that the widget settings form would get bloated. If we provide the weekdays setting if the frequency is weekly, we probably also have to consider all other possible combinations.

Don't close it yet, I'd like to think it over, but I don't promise an immediate solution. :wink:

Thanks for reporting - so this module finally got a little "documentation".
