### ISSUE TITLE
Removing 'exclude date'

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/repeating_dates#24]
It would be nice to be able to remove an 'exclude date'. Right now it is only possible to add.
There is of course work-arounds. Deleting it in the database, setting it to a past date.
Probably not a big deal, but I made a typo - therefore.

**Comment by indigoxela** [comment]
> It would be nice to be able to remove an 'exclude date'

There is. What it looks like may depend on your browser.

Example Firefox:
![remove-exclude](https://user-images.githubusercontent.com/842066/178466086-969c8e3c-1cfc-48f6-a317-844c63831f5a.png)

Example Chrome:
![remove-exclude-chrome](https://user-images.githubusercontent.com/842066/178466141-5acf5b45-a3fc-437f-9eb5-3c31b50306f0.png)

So you just empty the value and save the node. That's it.

> Deleting it in the database...

Oh no! Please don't. It's not necessary.

Which browser are you using?

**Comment by Egmund** [comment]
Oh yes - simple when you know. It works.
Thank you for such quick response.
