### ISSUE TITLE
Unpublish node with repeating dates via Bulk Operations causes repeating rule to be lost

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/repeating_dates#26]
If you unpublish a node using a repeating dates field by editing the node, setting the Published State to Draft and then saving the node then the repeating rule is preserved.

If you select the node in 'Manage Content' or another view with Bulk Operations and select "Unpublish Content" then the following warning is received and the repeating rule disappears.

Warning: implode(): Invalid arguments passed in repeating_dates_field_presave() (line 341 of /app/docroot/modules/contrib/repeating_dates/repeating_dates.module).

Immediately after the warning (i.e. same second), a notice appears in the log:

Notice: Undefined index: freq in _repeating_dates_build_rrule() (line 550 of /app/docroot/modules/contrib/repeating_dates/repeating_dates.module).

**Comment by indigoxela** [comment]
> ... warning is received and the repeating rule disappears.

Wow, that's quite destructive... (confirmed).

**Comment by indigoxela** [comment]
A PR is available for testing: #27

**Comment by yorkshire-pudding** [comment]
Thanks @indigoxela - I've tested this and it fixes the issue.

**Comment by indigoxela** [comment]
@yorkshire-pudding many thanks for reporting and testing.

I think, the severity of this bug warrants an immediate release.
