### ISSUE TITLE
Expose parts of the repeating definition to tokens

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/repeating_dates#28]
It would be good to be able to access parts of the repeating definition as tokens with the ability to customise the date format.

My use case is I'd like to use auto_nodetitle to generate meaningful titles based on the date span covered by the repeating schedule.  For example, "Team meeting - Jan 22 to Mar 22" (NB - I use another field on the calendar but want to be able to manage schedules more easily)

I don't know if this is even possible, or whether it would be easier to expose the components of the rule or the dates generated by the rule (I would only be interested in first and last).  I could work with whatever is easiest.

**Comment by indigoxela** [comment]
> I don't know if this is even possible...

I don't think so, no. Not without custom coding.

> ... whether it would be easier to expose the components of the rule ...

That would for sure be hard. A typical (simple) ICAL rule looks like this:

```
RRULE:FREQ=MONTHLY;BYSETPOS=1;BYDAY=TH;INTERVAL=1;COUNT=10;WKST=MO
```
So, out of the box (without using the php-rrule library) you won't be able to do anything useful with it.

BUT... you could eventually achive what you want with [Token Embed Views](https://backdropcms.org/project/token_embed_views) - just a thought, didn't try.

The human readable text for the rule probably won't be the right thing for you, I guess - too long.

**Comment by yorkshire-pudding** [comment]
Thanks for looking @indigoxela - I thought it might be a bit of a long shot

**Comment by indigoxela** [comment]
Hey, I just played with a view and got it working! It's not trivial, but no rocket science, either.

You need:

- nid - display hidden (to prevent aggressive aggregation to single result)
- dtstart - aggregation MIN, display hidden
- dtstart - aggregation MAX, override display (example: `from [field_dates_repeat_dtstart] to [field_dates_repeat_dtstart_1] `)

Then you need to turn on a contextual filter on nid (current nid).

Then you'd use the view token for that node's title... (didn't test).

**Comment by yorkshire-pudding** [comment]
Clever! - Thanks @indigoxela - I'll give that a shot

**Comment by yorkshire-pudding** [comment]
Thinking about that it won't work for creation of node, which is when I would want it. Good idea though.

**Comment by indigoxela** [comment]
> Thinking about that it won't work for creation of node...

No "nid" yet and no dates written to the db...

I may be completely wrong, but if I recall correctly, auto_nodetitle can catch that by delaying the title construction (by using register_shutdown_function).

**Comment by yorkshire-pudding** [comment]
While it does seem to have backdrop_register_shutdown_function:
(a) nothing is returned when creating, only after edit
(b) after edit, the view is returned but not as a straight text snippet (even when turning off all the wrappers etc I can), more like:
```
> Team<div class="view view-manage-events view-id-manage_events view-display-id-embed_meeting_schedule_date_range view-dom-id-bee4f069e8567007d55141bde23f6f87"> <div class="view-content"> <div > Jun 22…
```

I've raised a request for the ability to display a raw value, but it doesn't look like its been solved in D7 so maybe too hard.

Thanks anyway, it was worth a try and I've learned about another module.

**Comment by indigoxela** [comment]
Yikes, then of course, the views approach won't work at all.

Anyway, even if you coded it yourself, you'd probably still struggle with the "data not exist yet" problem.

One thing to consider for repeating_dates: maybe one single display format isn't sufficient. Possibly it's time to gather some feedback, what the most useful additional display formats could be. :wink: But that should be a different issue.
