### ISSUE TITLE
Additional display formats

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/repeating_dates#29]
Currently the formatter ships with a single display format: "Repeating date list".
That's sparse...

My problem: I don't know what the most useful additional format could be? Think of this issue as some sort of evaluation thing to figure out, what people need.

Feel free to suggest display formats here in a comment.

**Comment by yorkshire-pudding** [comment]
For long series, it may be more useful to display start and end instance dates together with a list (comma separated?) of exclusions

**Comment by indigoxela** [comment]
Suggestion:

`From [start] to [end], except for [1], [2]`

Discarded:

`Weekly, from [start] to [end], ...`

Problematic - think of frequencies like "every third Sunday". It should be easy to translate.


Possible available display options:

- Date format for start/end
- Date only format for excluded dates
- Append exceptions list or not?

**Comment by yorkshire-pudding** [comment]
@indigoxela - yes I think those options are helpful

**Comment by djzwerg** [comment]
Maybe it would make sense to have the choice to show only the next date instead of all?

**Comment by indigoxela** [comment]
> to show only the next date instead of all?

That might be a bit tricky because of node caching...

Have you tried views for that task? That should work.
