### ISSUE TITLE
Allow default start and to dates

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/repeating_dates#35]
A nice addition would be to allow default start and to dates, similar to how other date fields allow it:

![2023-08-29 10 19 58 hda-chrl-bd lndo site cc3c4a5b64ec](https://github.com/backdrop-contrib/repeating_dates/assets/1071483/fe3b4102-263a-4b96-a44f-bbf4e08612df)

**Comment by herbdool** [comment]
I've got a PR. Not sure if it's the best approach but it works. @indigoxela

**Comment by indigoxela** [comment]
So this expands things even more, to be more like the D7 dates module did things.

Have to think it over.

I know, that's quite opinionated, but usually I avoid to do things like the date module did. :wink:

**Comment by herbdool** [comment]
@indigoxela The nice thing about this PR is that it gives people a choice: people can leave the defaults blank, like now. Or they can set defaults if that works better with their workflow.
