### ISSUE TITLE
Some guidance on repeat count and number of values

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/repeating_dates#36]
Silly me. I was testing out the module by creating a repeating date field, setting it to unlimited values and leaving everything else default. Then when I was creating a node I left it at the default count given: 366. This gave me this error:

EntityStorageException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'field_date_and_time_dtstart' at row 250 in NodeStorageController->save() (line 512 of /app/core/modules/node/node.entity.inc).

Though I'm not quite sure why it's creating the error for one column. It should just be creating 366 rows. The column is int(11) so I'll look to see if that is too limited. I'm going to test some more.

At any rate, even if they're two different issues, maybe the default count should always be 1 or 2?

**Comment by indigoxela** [comment]
> maybe the default count should always be 1 or 2?

Ehm... I'm not sure if I get, what you're after...
You need as many values as potential "repeats". They get saved as individual values, so they're exposed to views and stuff.

Can you provide the steps to reproduce the EntityStorageException? That sounds weird, but I'm not sure how that happens. Following your steps (366 repeats), my node just saved a whole lot of values, but no error.

**Comment by herbdool** [comment]
There are two things I've mixed up here. I'll try to recreate the error again, next week.

The other thing about the count, is what appears to the user when creating a node. I found it surprising that if I don't change anything that it create 366 repeats. I think it would be better to allow admins to set a default count and end user can increase it as needed. I like to set the field values to unlimited because I don't know what kind of repeating events are needed. The majority are going to repeat only a handful but some might have many. Even so, I don't want people to accidentally create 366 repeats.

**Comment by indigoxela** [comment]
> if I don't change anything that it create 366 repeats

Only if you set the field global "Number of values" to _unlimited_, which isn't the default.

> I think it would be better to allow admins to set a default count and end user can increase it as needed

Admin can already set a default. :wink:  That's the usual behavior for field cardinality as provided by core.

> I like to set the field values to unlimited...

Technically spoken, "unlimited" is a misleading word. There's always a (performance) limit for the number of records, that get written to db simultaneously. I'd personally set a limit to a much lower number, like 50 or less. In real life - how many repeats would make sense, anyway?

Oh, and BTW, personally I rather use the "By default stop repeating by" "Date" setting, as that seems easier to understand.

**Comment by herbdool** [comment]
> Only if you set the field global "Number of values" to unlimited, which isn't the default.

Date_repeat in d7 sets it to unlimited values, but leaves the count blank when an end user is creating an event. I would like to be able to do that. 

I would like to set a default count that is low, *without* putting a hard limit on the number of values.

**Comment by indigoxela** [comment]
Sorry, that this module doesn't meet your requirements. Of course, you could always override all settings via hook_form_alter.

**Comment by herbdool** [comment]
I feel like I'm not explaining it well enough. My suggestion would be optional but at least it would allow for different needs. 

I'll be away from computers for a week, so hopefully I can provide a screenshot and PR next week.

**Comment by herbdool** [comment]
I also think I should create a new issue so as not to confuse a bug report with a feature request.

**Comment by indigoxela** [comment]
Re the exception, I belief, this has been fixed in #41

It was the year 2038 problem.
