### ISSUE TITLE
Allow repeating dates to be "first-class" date fields for Views so it can be used with calendar module

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/repeating_dates#37]
I'm trying to see what it would take to allow this to be used with [calendar](https://github.com/backdrop-contrib/calendar). That module requires the field to be available in Views Contextual Filter under the "Date: Date (node)" filter (there may be other requirements as well). (By the way, I was made aware, later that fullcalendar_views also exists - which also seems to work well, though I still the value of this issue).

In order to make it available, it will need at least the following added to `repeating_dates_field_views_data_views_data_alter()`:

```
foreach ($data as $base_table => &$table) {
      foreach ($table as $id => &$field) {
        foreach (array('field', 'sort', 'filter', 'argument') as $type) {
          if (isset($field[$type]) && isset($field[$type]['handler']) && ($field[$type]['handler'] == 'views_handler_' . $type . '_date')) {
            $field[$type]['is date'] = TRUE;
          }
        }
      }
    }
```

This adds `is date = TRUE` to each handler that's in the same function. But this isn't enough. There is a `hook_date_views_fields()` but it only applies to fields that *not* defined via Field API (see `_date_views_fields()`). We would need to adjust the array that that function creates, because it assumes that the "from/to" are `value` and `value2` but this module calls them `dtstart` and `dtend`. This might be where a Core PR comes in, because I think it would make sense to allow `hook_date_views_fields()` to adjust *any* date field. I can make that PR if needed.

Maybe that's enough to make this module a first-class "date"-type field. But I'll see.

**Comment by indigoxela** [comment]
Yeah, I saw, you've been busy working on the Calendar module lately. :+1: 
TBH, repeating_dates hasn't even been tested with that module, as it appeared to be abandoned for a while.

The [fullcalendar_views](https://github.com/backdrop-contrib/fullcalendar_views) module has full support for repeating_dates, though.

Switching to "value" and "value2" in repeating_dates isn't an option for me. The field column names "dtstart" and "dtend" have been chosen by intention. And it's also by intention, that this module's field type is a standalone field type, which doesn't share all the odd behavior of core date fields.

**Comment by herbdool** [comment]
@indigoxela I didn't say that you'd need to switch the column names, I said that it would be good that core's date module could support any date field, regardless of the column names. At least that's what I meant by:

> We would need to adjust the array that that function creates, because it assumes that the "from/to" are value and value2 but this module calls them dtstart and dtend. This might be where a Core PR comes in, because I think it would make sense to allow hook_date_views_fields() to adjust any date field. I can make that PR if needed.
