### ISSUE TITLE
Allow admins to set the default count separately from the maximum number of values

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/repeating_dates#38]
When adding this field, I propose that admins be able to set the default count separately from the maximum number of values. Currently, the default count is set to the maximum number of values.

Proposed:

Option to set the default count that appears when selecting "By default stop repeating by: count":

![2023-09-06 10 10 20 hda-chrl-bd lndo site 71d5e13d11dd](https://github.com/backdrop-contrib/repeating_dates/assets/1071483/0efd2693-f6f4-4997-b85e-a81d0ebbd2f5)

Then when setting the maximum number of values like this:

![2023-09-06 10 12 02 hda-chrl-bd lndo site 7bc44fe71a36](https://github.com/backdrop-contrib/repeating_dates/assets/1071483/a9532c79-c747-4f4b-914b-2b618eee631a)

the default count will show what was set in the option (and not 50):

![2023-09-06 10 17 39 hda-chrl-bd lndo site d1140fe4e385](https://github.com/backdrop-contrib/repeating_dates/assets/1071483/21f9f5d7-b924-4532-8e1f-6ab4cf7a4fc3)

The reason for this option is this helps prevent staff from accidentally creating 50 repeats, when they only meant to add a couple.

**Comment by herbdool** [comment]
I've created a PR @indigoxela

**Comment by indigoxela** [comment]
@herbdool great, many thanks. :pray:  Please note my comment on your PR.

**Comment by herbdool** [comment]
@indigoxela I've updated the PR.

**Comment by indigoxela** [comment]
@herbdool many thanks for your quick response. I've added some concerns re workflow.
