### ISSUE TITLE
Useful widget and formatter settings

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/repeating_dates#5]
Currently there are some basic widget settings.

- Collect or hide the "To" date fields (done)
- Default repeat mode (daily, weekly...) (done)
- Custom help text for exclude dates? (done)
- ???

To consider for the formatter settings:

- Show / hide the rule summary display (done)
- Date format setting (done)
- ???

Feedback is welcome. But please don't make it too complicated :stuck_out_tongue_winking_eye:

**Comment by yorkshire-pudding** [comment]
Could the formatter allow for the individual dates to be represented on a calendar (e.g FullCalendar View type)?  If I try to add this content type with a FullCalendar View format, I get:
Display "Block" requires at least one date field.

I think the UX for creating is great, but it would limit display choices and therefore use cases if can only display as list.

**Comment by indigoxela** [comment]
FullCalendar Views (module) only knows about core **date** fields, hence there's no support for this brand new field type (yet).

Note that the field type does ship with views support, so you can create all sorts of views displays (table, list...), also with custom date formats and pagination.

But that's actually out of the scope of this issue - which is about widget and formatter settings for *this* field type. Mind to create a new issue for alternate display methods?

**Comment by yorkshire-pudding** [comment]
> But that's actually out of the scope of this issue - which is about widget and formatter settings for _this_ field type. Mind to create a new issue for alternate display methods?

Done #11

**Comment by indigoxela** [comment]
Not much activity here, I guess, this can get closed.
