### ISSUE TITLE
Question... cardinality set to 366

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/repeating_dates#8]
repeating_dates.widget_form.inc

Line 24

It would make sense to set the max to 365, so at least a years worth of repeating dates would be possible...  1 per day including leap years.

**Comment by indigoxela** [comment]
> It would make sense to set the max to 365,...

Sure, why not. The important thing about it is that it can not be "-1", which is the value of `FIELD_CARDINALITY_UNLIMITED` and it also can't be "unlimited" - infinity won't work here, either. It controls the max of values that get written to the database at once. (300 is already unrealistically high.)
